name: Weather Push

on:
  schedule:
    - cron: '0 23 * * *'  # 日本时间早上8点
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install
        run: pip install requests

      - name: Run Script
        run: python main.py
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          SCKEY: ${{ secrets.SCKEY }}
